Repository Eumpa-Delivery/EUMPA-SERVER, pull requests merged in 2024-01, with the labels that each got.

#2 Deploy : Github Action Script 파일 작성
  .github/workflows/gradle.yml
  .gitignore
  src/main/resources/application.properties
Labels: 🌏 Deploy

#23 Feat : 회원가입 기능 프론트 연결 확인
  .github/workflows/gradle.yml
  src/main/java/com/eumpa/delivery/member/controller/MemberController.java
  src/main/java/com/eumpa/delivery/member/model/dto/JoinReqDTO.java
  src/main/java/com/eumpa/delivery/member/model/entity/Member.java
  src/main/java/com/eumpa/delivery/member/repository/MemberRepository.java
  src/main/java/com/eumpa/delivery/member/service/MemberService.java
  src/main/java/com/eumpa/delivery/member/service/impl/MemberServiceImpl.java
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
Labels: ✨ Feature

#24 Feat : 회원가입 기능 프론트 연결 확인
  .github/workflows/gradle.yml
  src/main/java/com/eumpa/delivery/member/controller/MemberController.java
  src/main/java/com/eumpa/delivery/member/model/dto/JoinReqDTO.java
  src/main/java/com/eumpa/delivery/member/model/entity/Member.java
  src/main/java/com/eumpa/delivery/member/repository/MemberRepository.java
  src/main/java/com/eumpa/delivery/member/service/MemberService.java
  src/main/java/com/eumpa/delivery/member/service/impl/MemberServiceImpl.java
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
Labels: ✨ Feature

#26 Deploy : 배포 설정 변경
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/eumpa/delivery/member/controller/MemberController.java
Labels: ⚙ Setting, 🌏 Deploy

#30 Deploy : gradle.yml 파일 수정
  .github/workflows/gradle.yml
Labels: 🌏 Deploy

#37 Docs : Swagger 및 ExceptionHandler 설정
  build.gradle
  src/main/java/com/eumpa/delivery/TestController.java
  src/main/java/com/eumpa/delivery/config/SwaggerConfig.java
  src/main/java/com/eumpa/delivery/error/exception/AuthException.java
  src/main/java/com/eumpa/delivery/error/exception/ChatException.java
  src/main/java/com/eumpa/delivery/error/exception/DeliveryException.java
  src/main/java/com/eumpa/delivery/error/handler/GlobalExceptionHandler.java
  src/main/java/com/eumpa/delivery/error/response/GlobalErrorResponse.java
  src/main/java/com/eumpa/delivery/error/type/AuthErrorCode.java
  src/main/java/com/eumpa/delivery/error/type/ChatErrorCode.java
  src/main/java/com/eumpa/delivery/error/type/DeliveryErrorCode.java
Labels: 📃 Documentation, ✨ Feature

#40 Docs : Swagger 및 ExceptionHandler 설정
  build.gradle
  src/main/java/com/eumpa/delivery/TestController.java
  src/main/java/com/eumpa/delivery/config/SwaggerConfig.java
  src/main/java/com/eumpa/delivery/error/exception/AuthException.java
  src/main/java/com/eumpa/delivery/error/exception/ChatException.java
  src/main/java/com/eumpa/delivery/error/exception/DeliveryException.java
  src/main/java/com/eumpa/delivery/error/handler/GlobalExceptionHandler.java
  src/main/java/com/eumpa/delivery/error/response/GlobalErrorResponse.java
  src/main/java/com/eumpa/delivery/error/type/AuthErrorCode.java
  src/main/java/com/eumpa/delivery/error/type/ChatErrorCode.java
  src/main/java/com/eumpa/delivery/error/type/DeliveryErrorCode.java
Labels: 📃 Documentation, ✨ Feature

#41 Docs : Swagger 및 ExceptionHandler 설정 (#40)
  build.gradle
  src/main/java/com/eumpa/delivery/TestController.java
  src/main/java/com/eumpa/delivery/config/SwaggerConfig.java
  src/main/java/com/eumpa/delivery/error/exception/AuthException.java
  src/main/java/com/eumpa/delivery/error/exception/ChatException.java
  src/main/java/com/eumpa/delivery/error/exception/DeliveryException.java
  src/main/java/com/eumpa/delivery/error/handler/GlobalExceptionHandler.java
  src/main/java/com/eumpa/delivery/error/response/GlobalErrorResponse.java
  src/main/java/com/eumpa/delivery/error/type/AuthErrorCode.java
  src/main/java/com/eumpa/delivery/error/type/ChatErrorCode.java
  src/main/java/com/eumpa/delivery/error/type/DeliveryErrorCode.java
Labels: 📃 Documentation, ✨ Feature

#46 Feat : 회원가입 #42
  build.gradle
  src/main/java/com/eumpa/delivery/member/controller/MemberController.java
  src/main/java/com/eumpa/delivery/member/model/dto/JoinReqDTO.java
  src/main/java/com/eumpa/delivery/member/model/entity/Member.java
  src/main/java/com/eumpa/delivery/member/model/type/EmailAuthStatus.java
  src/main/java/com/eumpa/delivery/member/model/type/MemberRole.java
  src/main/java/com/eumpa/delivery/member/model/type/MemberStatus.java
  src/main/java/com/eumpa/delivery/member/repository/MemberRepository.java
  src/main/java/com/eumpa/delivery/member/service/MemberService.java
  src/main/java/com/eumpa/delivery/member/service/impl/MemberServiceImpl.java
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
Labels: ✨ Feature
